version: '2'
services:
  web:
    build: .
    depends_on:
      - postgis
    environment:
      - DATABASE_URL=postgis://mapzen:mapzen@postgis/elevation
    env_file: .env
    volumes:
      - .:/opt/marblecutter/
    ports:
      - "8000:8000"
    links:
      - postgis
    command: python app.py
  postgis:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=mapzen
      - POSTGRES_PASSWORD=mapzen
      - POSTGRES_DB=elevation
volumes:
  pgdata:
